version: 2
jobs:
  lint:
    docker:
      # 使用するDockerイメージ  
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: |
              #仮想環境作成
              python -m venv venv
              source ./venv/bin/activate
              # 文法チェックツールflake8をインストール
              pip install -r requirements.txt
              # flake8実行
              flake8 ./flaskr
  test:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: |
              python -m venv venv
              source ./venv/bin/activate
              # テストランナーpytestをインストール
              # pip install pytest
              # フレームワークflaskをインストール
              pip install -r requirements.txt
              # pip install flask
              # pytest実行
              pytest --junit-xml=test-results/pytest.xml
      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint
      - test:
          # lintが成功した場合のみtestを実行
          requires:
            - lint
      - deploy:
          requires:
            - test
          # masterブランチの場合のみdeployを実行
          filters:
            branches:
              only: master
